### ISSUE TITLE
MappingMixIn import error

### ISSUE THREAD

**Issue by akeley98** [leonardt/fault#17]
```
>>> import fault
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mantissa/Documents/aha/fault/fault/__init__.py", line 1, in <module>
    from .tester import Tester
  File "/home/mantissa/Documents/aha/fault/fault/tester.py", line 4, in <module>
    from .verilator_target import VerilatorTarget
  File "/home/mantissa/Documents/aha/fault/fault/verilator_target.py", line 2, in <module>
    from fault.test_vectors import generate_function_test_vectors
  File "/home/mantissa/Documents/aha/fault/fault/test_vectors.py", line 7, in <module>
    import pytest
  File "/home/mantissa/.local/lib/python3.6/site-packages/pytest.py", line 20, in <module>
    from _pytest.mark import MARK_GEN as mark, param
  File "/home/mantissa/.local/lib/python3.6/site-packages/_pytest/mark/__init__.py", line 4, in <module>
    from .structures import (
  File "/home/mantissa/.local/lib/python3.6/site-packages/_pytest/mark/structures.py", line 9, in <module>
    from ..compat import NOTSET, getfslineno, MappingMixin
ImportError: cannot import name 'MappingMixin'
```

**Comment by David-Durst** [comment]
Pytest was out of date. Updating pytest fixed this.
